# Generated by Django 4.1.5 on 2023-02-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='malls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mallname', models.CharField(max_length=50)),
                ('malllocation', models.CharField(max_length=50)),
                ('mallbudget', models.FloatField()),
                ('openingdate', models.DateField()),
                ('openingguest', models.CharField(max_length=50)),
            ],
        ),
    ]
