# Generated by Django 4.1.5 on 2023-02-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('Gender', models.CharField(choices=[('--', '---'), ('m', 'Male'), ('f', 'Female'), ('nan', 'None Of the above')], max_length=20)),
                ('mobileno', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dateofbirth', models.DateField()),
                ('HighestQualification', models.CharField(max_length=60)),
                ('PassedYear', models.CharField(choices=[('--', '---'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=10)),
                ('Percentage', models.IntegerField()),
                ('Select_course', models.CharField(choices=[('-', '---'), ('aws', 'AWS'), ('data', 'Data Science'), ('ja', 'Java'), ('fend', 'FrontEnd'), ('fullsta', 'Full Stack Python Developer'), ('full', 'Full Stack Java Developer')], max_length=40)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
